version: '2'

services:
  split-the-bill:
    image: split-the-bill:0.1.0
    container_name: split-the-bill
    restart: always
    build: .
    working_dir: /app/split-the-bill
    environment:
      - TOKEN=${TOKEN_PROD}